remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ErasmusMG
description: ErasmusMG is a 2D game development framework written on top of MonoGame in C#. It is a collection of very useful classes and methods to help create any 2D game, from platformers to top-down shooters.
